M48
; DRILL file {KiCad 9.0.3} date 2025-08-03T17:59:29+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-03T17:59:29+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X136.36Y-128.645
X142.14Y-128.645
T2
X126.7Y-82.55
X127.0Y-132.0
X154.0Y-82.5
X154.0Y-132.0
M30
